name: Build gProfiler on Windows

permissions:
  contents: read

on: pull_request

jobs:
  build-executable:
   runs-on: windows-latest
   steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: run the build script
        run: .\scripts\windows\build.bat

      - name: check gprofiler build
        run: .\app\dist\gprofiler.exe -h
